services:
  postgresql:
    image: postgres
    container_name: postgres-container
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    networks:
      - app-network

  tomcat:
    image: tomcat
    container_name: tomcat-container
    restart: always
    volumes:
      - ./target/rss-web-reader.war:/usr/local/tomcat/webapps/rss-web-reader.war
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  appvolume: {}

networks:
  app-network: